/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package image;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author collo k
 */
public class details extends javax.swing.JFrame {
Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form details
     */
    public details() {
        initComponents();
        Update_Table();
        Contacts();
        Time();
    }
         public Connection getConnection(){
        Connection con;
        try{
            Class .forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bict","root","collins24");
            return con;
        }catch(Exception e){
            e.printStackTrace();
            return null;
            
        }
    }
             private void  Update_Table(){
         Connection con=getConnection();
         PreparedStatement pst;
         ResultSet rs;
         
         try{
             String query="SELECT * FROM `image2`";
             pst=con.prepareStatement(query);
             rs=pst.executeQuery();
             table1.setModel(DbUtils.resultSetToTableModel(rs));
             
             
       
        
             
             
             
             
             
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
             
             
         }
     }
         private void  Contacts(){
         Connection con=getConnection();
         PreparedStatement pst;
         ResultSet rs;
         
         try{
             String query="SELECT * FROM `contacts`";
             pst=con.prepareStatement(query);
             rs=pst.executeQuery();
             table2.setModel(DbUtils.resultSetToTableModel(rs));
             
             
       
        
             
             
             
             
             
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
             
             
         }
     }
       private void  Time(){
         Connection con=getConnection();
         PreparedStatement pst;
         ResultSet rs;
         
         try{
             String query="SELECT * FROM `timetable`";
             pst=con.prepareStatement(query);
             rs=pst.executeQuery();
             table3.setModel(DbUtils.resultSetToTableModel(rs));
             
             
       
        
             
             
             
             
             
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
             
             
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comp2 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        bict2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        comp4 = new javax.swing.JTextField();
        math1 = new javax.swing.JTextField();
        math4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("enter your registration number");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 215, 28);
        jPanel2.add(comp2);
        comp2.setBounds(110, 240, 109, 30);

        jTabbedPane1.addTab("assgnments", jTabbedPane3);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jTabbedPane2.addTab("tab1", jScrollPane1);

        jTabbedPane1.addTab("study resources", jTabbedPane2);

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table3);

        jTabbedPane4.addTab("tab1", jScrollPane3);

        jTabbedPane1.addTab("time table", jTabbedPane4);

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table2);

        jTabbedPane1.addTab("contacts", jScrollPane2);

        jPanel2.add(jTabbedPane1);
        jTabbedPane1.setBounds(230, 10, 265, 212);

        bict2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bict2ActionPerformed(evt);
            }
        });
        jPanel2.add(bict2);
        bict2.setBounds(110, 180, 109, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "eg-33547", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 51))); // NOI18N

        search.setBackground(new java.awt.Color(153, 153, 255));
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(10, 30, 164, 81);
        jPanel2.add(comp4);
        comp4.setBounds(110, 130, 109, 30);
        jPanel2.add(math1);
        math1.setBounds(110, 300, 109, 30);
        jPanel2.add(math4);
        math4.setBounds(110, 370, 110, 30);

        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("COMP404");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 130, 70, 30);

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("BICT201");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 184, 50, 20);

        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("COMP211");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 250, 60, 20);

        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("MATH141");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 310, 60, 20);

        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("MATH454");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 374, 60, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\collo k\\Desktop\\ireri\\reading-book-rainy-day-cozy-animated-gif.gif")); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 520, 510);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\collo k\\Downloads\\1469464710_Log Out.png")); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(380, 490, 120, 25);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\collo k\\Downloads\\1469464710_Log Out.png")); // NOI18N
        jMenu3.setText("exit");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bict2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bict2ActionPerformed
       
        
// TODO add your handling code here:
    }//GEN-LAST:event_bict2ActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        PreparedStatement pst;
        Connection con =getConnection();
        ResultSet rs;   
        try{
            String sql="select * from marks where regno=?";
            pst=con.prepareStatement(sql);
            pst.setString(1 ,search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                
                
                 String add1=rs.getString("comp404");
                comp4.setText(add1);
                String add2=rs.getString("bict201");
                bict2.setText(add2);
                 String add3=rs.getString("comp211");
                comp2.setText(add3);
                 String add4=rs.getString("math141");
                math1.setText(add4);
                String add5=rs.getString("math454");
                math4.setText(add5);
               
                
            }
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "this student is not in this database");
            search.setText("");
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_searchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    login n=new login();
    n.setVisible(true);
    setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
    accounts b=new accounts();
    b.setVisible(true);
    setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table2MouseClicked

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        int row=table1.getSelectedRow();
        String laikipia=(table1.getModel().getValueAt(row, 2).toString());

        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+laikipia);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_table1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
    accounts m= new accounts();
    m.setVisible(true);
    setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bict2;
    private javax.swing.JTextField comp2;
    private javax.swing.JTextField comp4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField math1;
    private javax.swing.JTextField math4;
    private javax.swing.JTextField search;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    // End of variables declaration//GEN-END:variables
}
