/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package image;
import com.sun.glass.events.KeyEvent;
import image.welcom;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author collo k
 */
public class User_Login extends javax.swing.JFrame {

    /**
     * Creates new form User_Login
     */
    public User_Login() {
        initComponents();
    }

    
    public Connection getConnection(){
        Connection con;
        try{
            Class .forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bict","root","collins24");
            return con;
        }catch(Exception e){
            e.printStackTrace();
            return null;
            
        }
    }
    

       

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField_Password = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField_EmailAdress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "admin", "lecturer", "student" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(380, 400, 80, 20);

        jTextField_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_PasswordKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField_Password);
        jTextField_Password.setBounds(230, 220, 230, 50);

        jPanel2.setLayout(null);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(520, 120, 150, 160);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\collo k\\Downloads\\1467744774_User.png")); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 150, 160);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(520, 100, 150, 160);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 330, 100, 40);

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Book", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\collo k\\Downloads\\1469464752_Key.png")); // NOI18N
        jLabel3.setText("password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 230, 130, 30);
        jPanel1.add(jTextField_EmailAdress);
        jTextField_EmailAdress.setBounds(230, 130, 230, 40);

        jLabel2.setFont(new java.awt.Font("Khmer UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 130, 120, 40);

        jButton2.setText("homepage");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(713, 523, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\collo k\\Desktop\\ict\\WM2A4168-606_M.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 0, 1330, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
       
        Statement st;
        PreparedStatement ps;
        Connection con=getConnection();
        try{ 
      
          ps=con.prepareStatement( "SELECT `emailaddress`, `password` FROM `collo`WHERE `emailaddress`=? AND `password`=? ");
          
          ps.setString(1, jTextField_EmailAdress.getText());
          ps.setString(2, String.valueOf(jTextField_Password.getText()));
          ResultSet result=ps.executeQuery();
          if(result.next()){
           
            JOptionPane.showMessageDialog(null,jTextField_EmailAdress.getText()+ " Welcome Again");
            
            welcom w=new welcom();
            w.setVisible(true);
            jTextField_EmailAdress.setText("");
            jTextField_Password.setText("");
          }else{
              JOptionPane.showMessageDialog(null, "incorrect username or password try again", "message", JOptionPane.ERROR_MESSAGE);
              jTextField_Password.setText("");
              
          }

       }
       catch(Exception ex){
           
           ex.printStackTrace();
           
       }
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PasswordKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                  
        Statement st;
        PreparedStatement ps;
        Connection con=getConnection();
        try{ 
      
          ps=con.prepareStatement( "SELECT `emailaddress`, `password` FROM `collo`WHERE `emailaddress`=? AND `password`=? ");
          
          ps.setString(1, jTextField_EmailAdress.getText());
          ps.setString(2, String.valueOf(jTextField_Password.getText()));
          ResultSet result=ps.executeQuery();
          if(result.next()){
           
            JOptionPane.showMessageDialog(null,jTextField_EmailAdress.getText()+ " Welcome Again");
            
            welcom w=new welcom();
            w.setVisible(true);
            jTextField_EmailAdress.setText("");
            jTextField_Password.setText("");
          }else{
              JOptionPane.showMessageDialog(null, "incorrect username or password try again", "message", JOptionPane.ERROR_MESSAGE);
              jTextField_Password.setText("");
              
          }

       }
       catch(Exception ex){
           
           ex.printStackTrace();
           
       }
        
       }
    }//GEN-LAST:event_jTextField_PasswordKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    accounts a=new accounts();
    a.setVisible(true);
    setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_EmailAdress;
    private javax.swing.JPasswordField jTextField_Password;
    // End of variables declaration//GEN-END:variables
}
