/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package image;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author collo k
 */
public class welcom extends javax.swing.JFrame {

    /**
     * Creates new form welcom
     */
    public welcom() {
        initComponents();
        CurrentDate();
        Show_Users_In_Jtable();
    }
    
    public Connection getConnection(){
        Connection con;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bict","root","collins24");
            return con;
        }catch(Exception e){
            e.printStackTrace();
            return null;
        }
        
    }
     public ArrayList<Image> getUsersList(){
        ArrayList<Image> usersList =new ArrayList<Image>();
        Connection connection=getConnection();
        String Querry ="SELECT * FROM `imag`";
        Statement st;
        ResultSet rs;
        
        try{
            st=connection.createStatement();
            rs=st.executeQuery(Querry);
            Image user;
            while(rs.next()){
                user=new Image(rs.getInt("id"),rs.getString("name"),rs.getString("regno"),rs.getString("school"),rs.getString("course"),rs.getString("status"));
                usersList.add(user);
            }
            
        }catch(Exception e){
            e.printStackTrace();
            
        }
        return usersList;
    }
     public void Show_Users_In_Jtable(){
         ArrayList<Image> list=getUsersList();
          DefaultTableModel model = (DefaultTableModel)jTable_View_Users.getModel();
        Object[] row=new Object[6];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getID();
            row[1]=list.get(i).getName();
            row[3]=list.get(i).getRegno();
            row[2]=list.get(i).getSchool();
            row[4]=list.get(i).getCourse();
           
            row[5]=list.get(i).getStatus();
            
            model.addRow(row);
            
        }
         
     }
     public void executeSQLQuery(String query,String Message){
        Connection con =getConnection();
        Statement st;
        try{
            st=con.createStatement();
            if((st.executeUpdate(query)) ==1){
                DefaultTableModel model = (DefaultTableModel)jTable_View_Users.getModel();
                model.setRowCount(0);
                Show_Users_In_Jtable();
                
                JOptionPane.showMessageDialog(null, "Data "+Message+" succefully");
                
            }else {
                JOptionPane.showMessageDialog(null, "Data not "+Message);
            }
                
        }catch(Exception ex){
         ex.printStackTrace();
        }     
        
    } 
    public void CurrentDate(){

      Thread clock=new Thread(){
      public void run(){
          for(;;){
        Calendar cal=new GregorianCalendar();
      int month=cal.get(Calendar.MONTH);
      int year=cal.get(Calendar.YEAR);
      int day=cal.get(Calendar.DAY_OF_MONTH);
      date_txt.setText("Date"+day+"/"+(month+1)+"/"+year);
      int minute=cal.get(Calendar.MINUTE);
      int hour=cal.get(Calendar.HOUR_OF_DAY);
      int seconds=cal.get(Calendar.SECOND);
      time_txt.setText("Time"+hour+":"+(minute+1)+":"+seconds);
      
              try {
                  sleep(1000);
              } catch (InterruptedException ex) {
                  Logger.getLogger(welcom.class.getName()).log(Level.SEVERE, null, ex);
              }
          }
      }
      };
      clock.start();
      
      
      
   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField_Regno = new javax.swing.JTextField();
        jTextField_School = new javax.swing.JTextField();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_ID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Course = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Status = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        Insert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_View_Users = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        CLEAR = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        date_txt = new javax.swing.JMenu();
        time_txt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Details..", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(51, 0, 204))); // NOI18N

        jLabel1.setText("ID");

        jLabel2.setText("NAME");

        jLabel3.setText("REG/NO");

        jLabel4.setText("SCHOOL");

        jLabel5.setText("COURSE");

        jLabel7.setText("STATUS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Regno, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jTextField_Name)
                            .addComponent(jTextField_ID)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_School)
                            .addComponent(jTextField_Course)
                            .addComponent(jTextField_Status))))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Regno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_School, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Course, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Status, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 70, 250, 320);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUTONS..", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(51, 0, 255))); // NOI18N

        Update.setIcon(new javax.swing.ImageIcon("C:\\Users\\collo k\\Downloads\\1469464763_Refresh.png")); // NOI18N
        Update.setText("UPDATE");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Refresh.setIcon(new javax.swing.ImageIcon("C:\\Users\\collo k\\Downloads\\1469464745_Synchronize.png")); // NOI18N
        Refresh.setText("REFRESH");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        Insert.setIcon(new javax.swing.ImageIcon("C:\\Users\\collo k\\Downloads\\1469464736_Add.png")); // NOI18N
        Insert.setText("INSERT");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Refresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(Delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Insert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(310, 50, 140, 230);

        jTable_View_Users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Regno", "School", "Course", "Status"
            }
        ));
        jTable_View_Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_View_UsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_View_Users);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(500, 0, 470, 250);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\collo k\\Downloads\\1469464731_Search.png")); // NOI18N
        jLabel6.setText("Search..");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 10, 90, 30);

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(130, 10, 130, 30);

        CLEAR.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        CLEAR.setForeground(new java.awt.Color(255, 51, 0));
        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });
        jPanel1.add(CLEAR);
        CLEAR.setBounds(340, 303, 100, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 153));
        jLabel8.setText("Student details press next");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(730, 270, 250, 30);

        next.setBackground(new java.awt.Color(255, 204, 204));
        next.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        next.setText("NEXT");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next);
        next.setBounds(850, 310, 90, 50);

        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(850, 380, 90, 30);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        date_txt.setForeground(new java.awt.Color(255, 0, 0));
        date_txt.setText("Date");
        jMenuBar1.add(date_txt);

        time_txt.setForeground(new java.awt.Color(255, 0, 0));
        time_txt.setText("Time");
        jMenuBar1.add(time_txt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
  String query="UPDATE `imag` SET `name`='"+jTextField_Name.getText()+"',`regno`='"+jTextField_Regno.getText()+"',`school`='"+jTextField_School.getText()+"',`status`='"+jTextField_Status.getText()+"',`course`='"+jTextField_Course.getText()+"' WHERE `id` = "+jTextField_ID.getText();
  executeSQLQuery(query,"updated");
        


// TODO add your handling code here:
    }//GEN-LAST:event_UpdateActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshActionPerformed

    private void jTable_View_UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_View_UsersMouseClicked
                int i=jTable_View_Users.getSelectedRow();
        TableModel model=jTable_View_Users.getModel();
        jTextField_ID.setText(model.getValueAt(i, 0).toString());
        jTextField_Name.setText(model.getValueAt(i, 1).toString());
        jTextField_Regno.setText(model.getValueAt(i, 2).toString());
        jTextField_School.setText(model.getValueAt(i, 3).toString());
        jTextField_Course.setText(model.getValueAt(i, 4).toString());
        jTextField_Status.setText(model.getValueAt(i, 5).toString());
        
// TODO add your handling code here:
    }//GEN-LAST:event_jTable_View_UsersMouseClicked

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        String query="INSERT INTO `imag`( `name`, `regno`, `school`, `status`, `course`) VALUES ('"+jTextField_Name.getText()+"','"+jTextField_Regno.getText()+"','"+jTextField_School.getText()+"','"+jTextField_Status.getText()+"','"+jTextField_Course.getText()+"')";
        executeSQLQuery(query,"inserted");
        Student w=new Student();
        w.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_InsertActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        String query="DELETE FROM `imag` WHERE id="+jTextField_ID.getText();
        executeSQLQuery(query,"deleted");
// TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
    jTextField_Name.setText("");
    jTextField_ID.setText("");
    jTextField_Course.setText("");
    jTextField_Regno.setText("");
    jTextField_Status.setText("");
    jTextField_School.setText("");
        
// TODO add your handling code here:
    }//GEN-LAST:event_CLEARActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        PreparedStatement pst;
        Connection con =getConnection();
        ResultSet rs;
        try{
            String sql="select * from imag where regno=?";
            pst=con.prepareStatement(sql);
            pst.setString(1 ,txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("id");
                jTextField_ID.setText(add1);
                String add2=rs.getString("name");
                jTextField_Name.setText(add2);
                 String add3=rs.getString("regno");
                jTextField_Regno.setText(add3);
                String add4=rs.getString("school");
                jTextField_School.setText(add4);
                 String add5=rs.getString("course");
                jTextField_Course.setText(add5);
                 String add6=rs.getString("status");
                jTextField_Status.setText(add6);
                
            }
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "this stident is not in this database");
            
        }
                try{
            String sql="select * from imag where name=?";
            pst=con.prepareStatement(sql);
            pst.setString(1 ,txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("id");
                jTextField_ID.setText(add1);
                String add2=rs.getString("name");
                jTextField_Name.setText(add2);
                 String add3=rs.getString("regno");
                jTextField_Regno.setText(add3);
                String add4=rs.getString("school");
                jTextField_School.setText(add4);
                 String add5=rs.getString("course");
                jTextField_Course.setText(add5);
                 String add6=rs.getString("status");
                jTextField_Status.setText(add6);
                
            }
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "this student is not in this database");
            
        }
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_txt_searchKeyReleased

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        Student w=new Student();
        w.setVisible(true);   
        
        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    accounts a=new accounts();
    a.setVisible(true);
    setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Insert;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Update;
    private javax.swing.JMenu date_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_View_Users;
    private javax.swing.JTextField jTextField_Course;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Regno;
    private javax.swing.JTextField jTextField_School;
    private javax.swing.JTextField jTextField_Status;
    private javax.swing.JButton next;
    private javax.swing.JMenu time_txt;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
